config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :poll_answers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user_token' => 'user_token#create'

  root to: 'statics#home'

  as :user do
    # sessions
    get     'login',  to: 'devise/sessions#new',      as: :new_user_session
    post    'login',  to: 'devise/sessions#create',   as: :user_session
    delete  'logout', to: 'devise/sessions#destroy',  as: :destroy_user_session

    #registrations
    get   'users/cancel', to: 'devise/registrations#cancel',        as: :cancel_user_registration
    get   :signup,        to: 'devise/registrations#new',           as: :new_user_registration
    get   :profile,       to: 'devise/registrations#edit',          as: :edit_user_registration
    patch :profile,       to: 'devise_custom/registrations#update', as: :update_user_registration
  end
  devise_for :users, skip: [:sessions], controllers: { registrations: 'devise_custom/registrations' }


  get '/dashboard' , to: 'dashboard#index'
  get :dashboard, to: 'dashboard#index', as: :dashboard_index


 # get '/events/invite_event' , to: 'events#invite_event'
  get '/events/uninvite_event' , to: 'events#uninvite_event'
  get '/events/invite_app' , to: 'events#invite_app'
  get '/events/accept_event/:id' , to: 'events#accept_event', as: :accept_event_invite

  get '/events/qrcode/:id', to: 'events#qrcode', as: 'qrcode_event'
  get '/event_instances/qrcode/:id', to: 'event_instances#qrcode', as: 'qrcode_event_instance'
  post '/attendances/attended/', to: 'attendances#attended', as: 'attendances_attended'
  get '/attendances/doneattendance/', to: 'attendances#doneattendance', as: 'attendances_doneattendance'

  resources :events
  resources :event_instances, only: :destroy

  resources :events do
    member do
      get   :invite_event
      post  :invite_event_errors
      post  :accept_invitation_event
      post  :invite_app_action
      delete  :remove_invite
      delete   :leave_event
    end
  end
  resources :event_instances
  resources :polls do
    member do
      get :vote
    end
  end
  resources :forum_threads
  resources :attachments
  resources :comments
  resources :attendances



  # api
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events do
        post :invite, on: :member
      end
      resources :event_instances do
        post :mark_present, on: :member
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is? :admin
      can :manage, :all
    elsif user.is? :regular
      can :manage, Event, user_id: user.id
      can :manage, EventInstance, event: { user_id: user.id }
      can :manage, Attachment, event: { user_id: user.id }
      can :show, Attachment
      can :manage, ForumThread, event: { user_id: user.id }
      can :manage, ForumThread, user_id: user.id
      can :manage, Comment, forum_thread: { event: { user_id: user.id } }
      can :manage, Comment, forum_thread: { user_id: user.id }
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to      :event
  mount_uploader  :file,  FileUploader # Tells rails to use this uploader for this model.
  #validates       :user,        presence: true # Make sure the user is event admin.
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event_instance
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread
  has_ancestry

  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_instances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invited_users, through: :invitations, source: :user
  has_many :polls, dependent: :destroy
  has_many :forum_threads, dependent: :destroy
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :event_instances
  validates :name, presence: true

  def self.RECURRENT_DAYS
    {
      "No recurrent": 0,
      "Sunday": 1,
      "Monday": 2,
      "Tuesday": 3,
      "Wednesday": 4,
      "Thursday": 5,
      "Friday": 6,
      "Saturday": 7
    }
  end
end

app/models/event_instance.rb
class EventInstance < ApplicationRecord
  belongs_to :event
  has_many :attendances, dependent: :destroy
  validates :date, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :event
  has_many :poll_answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :name, presence: true
end

app/models/poll_answer.rb
class PollAnswer < ApplicationRecord
  belongs_to :poll
  validates :title, presence: true
  
  

def default_values
  self.voteCount = 0
end

def name
    "#{title}"
end

end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic

  ROLES = %w[ admin regular ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable

  alias_method :authenticate, :valid_password?

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :events, dependent: :destroy
  has_many :event_instances, through: :events
  has_many :attendances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :forum_threads, dependent: :destroy
  has_many :comments, dependent: :destroy

  def is?(role)
    roles.include?(role.to_s)
  end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def self.from_token_payload payload
    self.find payload["user_id"]
  end

  def to_token_payload
    {
      user_id: id.to_s,
      custom: {
        name: username,
        email: email
      }
    }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
    
    belongs_to :poll
   
   
    def default_values
      self.userId = -1
    end
    
    def default_values
      self.pollAnswerId = -1
    end
  
        
end

app/helpers/comments_helper.rb
module CommentsHelper

  def render_comments comments
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, render_comments(sub_comments), class: "nested-comments")
    end.join.html_safe
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
      <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/general_helper.rb
module GeneralHelper

  def set_title

  end

end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QRme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body class="<%= "#{params[:controller].sub("/", " ")} #{params[:action]}" %>">
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QRme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body class="<%= "#{params[:controller].sub("/", " ")} #{params[:action]}" %>">
    <div class="row">
      <%= render 'shared/nav_bar' %>
      <div class="content col-xs-10">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QRme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <body class="<%= "#{params[:controller].sub("/", " ")} #{params[:action]}" %>">
    <div class="devise-form-container">
      <div class="devise-form">
        <div class="border-top"></div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_attachments_list.html.erb
<% @event.attachments.each do |a| %>
    <div class="poll-container">
        <span class="name">
            <%= link_to a.name, attachment_path(a) %>
        </span>
        <span class="actions">
            <%= link_to attachment_path(a) do %>
            <%= fa_icon "download" %>
            <% end %>
            <% if can? :manage, a %>
                <%= link_to attachment_path(a), method: :delete,
                data: {confirm: "Are you sure?"
                }, remote: true, title: "Delete" do %>
                <%= fa_icon "trash" %> 
                <% end %>
            <% end %>
        </span>
    </div>
<% end %>

app/views/shared/_avatar.html.erb
<div class="profile-image">
  <%= image_tag User.find(current_user.id).gravatar_url(
    default: "https://s3.amazonaws.com/qrme/assets/happy_face.png"
  ) %>
</div>

app/views/shared/_devise_form_errors.html.erb
<div class="alert alert-danger alert-dismissible form-errors">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <%= errors %>
</div>

app/views/shared/_events_instances_list.html.erb
 <table class="table">
    <tr>
        <th>Date</th>
        <th>Location</th>
        <th># of Attendees</th>
        <th>Mark Attendance</th>
        <th>Actions</th>
    </tr>
    <% @event.event_instances.each do |ei| %>
        <tr>
            <td>
                <%= ei.date.strftime "%b %e, %Y @ %l:%M %P"  %>
            </td>
            <td>
                <%= ei.location %>
            </td>
            <td>
                <%= ei.attendances.count %>
            </td>
            <td>
                <%= link_to  edit_attendance_path(id: ei), class: "new-instance-button",
                remote: true do %>
                <%= fa_icon "check" %>  <% end %>
            </td>
            <td>
                <%= link_to qrcode_event_instance_path(id: ei.id), class: "new-instance-button",
                remote: true do %>
                <%= fa_icon "print" %> <% end %> | 
                <%= link_to edit_event_instance_path(id: ei.id), class: "new-instance-button",
                remote: true do %>
                <%= fa_icon "pencil" %> <% end %> | 
                <%= link_to event_instance_path(ei), method: :delete,
                data: { confirm: "Are you sure?",
                message: "The event's information will be lost and cannot be recovered.",
                }, remote: true, title: "Delete" do %>
                <%= fa_icon "trash" %> <% end %>
            </td>
        </tr>
    <% end %>
</table>

app/views/shared/_form_errors.html.erb
<% if object.errors.count > 0 %>
  <div class="alert alert-danger alert-dismissible form-errors">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul>
      <% object.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_forum_threads_list.html.erb
<% @event.forum_threads.each do |ft| %>
  <div class="forum-container">
    <span class="name">
      <%= link_to ft.title, forum_thread_path(ft) %>
    </span>
    <span class="actions">
      <% if can? :manage, ft %>
        <%= link_to edit_forum_thread_path(ft), remote: true, title: "Edit" do %>
          <%= fa_icon "pencil" %>
        <% end %>
        <%= link_to forum_thread_path(ft), method: :delete,
        data: { confirm: "Are you sure?",
        message: "The forums's information will be lost and cannot be recovered.",
        }, remote: true, title: "Delete" do %>
          <%= fa_icon "trash" %>
        <% end %>
      <% end %>
    </span>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="jumbotron main-header">
  <%= render "shared/main_nav_bar" %>
  <h1 class="main-subtitle">QRme makes planning events easier</h1>
  <h3 class="secondary-subtitle">QRme offers a simple and intuitive way of planning events,
    inviting friends, and staying in touch with invitees</h3>
  <%= link_to "Sign Up", new_user_registration_path,
    class: "btn btn-default active btn-lg sign-up-btn" %>
</div>

app/views/shared/_main_nav_bar.html.erb
<nav class="navbar main-nav-bar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#main-nav-bar"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "icon_light.svg", alt: "QRme" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="main-nav-bar">
      <ul class="nav navbar-nav navbar-right">
        <li class="home">
          <%= link_to "Home", root_path, class: "active" %>
        </li>

        <li class="dashboard">
          <%= link_to "Dashboard", dashboard_index_path, class: "active" %>
        </li>

        <li class="log-in">
          <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Login", new_user_session_path %>
          <% end %>
        </li>

      </ul>
    </div>

  </div>
</nav>

app/views/shared/_nav_bar.html.erb
<div class="col-xs-2 dashboard-sidebar">
  <%= image_tag "icon_color.svg", alt: "QRme", class: "dashboard-logo" %>
  <div class="profile-container">
    <%= render 'shared/avatar' %>
    <%= link_to edit_user_registration_path, class: "profile", remote: true do %>
      <%= fa_icon "cog", class: "spin" %>
    <% end %>
    <span class="username"><%= current_user.username.upcase %></span>
  </div>
  <ul class="nav nav-pills nav-stacked">
    <li class="events-menu-item">
      <%= link_to dashboard_index_path do %>
        <%= fa_icon "calendar" %> Events
      <% end %>
    </li>
    <% if current_user.is? :admin %>
      <li>
        <%= link_to "/admin" do %>
          <%= fa_icon "tachometer" %> Admin Panel
        <% end %>
      </li>
    <% end %>
    
      <li>
         <%= link_to events_invite_app_path, title: "Invite friends to app", remote: true do %>
         <%= fa_icon "bullhorn" %> Invite friends
        <% end %>
      </li>
      
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <%= fa_icon "sign-out" %> Log Out
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_poll_answers_list.html.erb
<% @poll.poll_answers.each do |ft| %>
  <div class="poll-container">
    <span class="name">
      <%= link_to ft.title, poll_answer_path(ft) %>
    </span>
    <span class="actions">
      <%= link_to poll_answer_path(ft), method: :delete,
      data: { confirm: "Are you sure?",
      message: "The poll answer's information including votes will be lost and cannot be recovered.",
      }, remote: true, title: "Delete" do %>
        <%= fa_icon "trash" %>
      <% end %>
    </span>
  </div>
<% end %>

app/views/shared/_poll_answers_table.html.erb
 <table class="table" width="50">
  
      <tr>
        <th>Poll Answer</th>
        <th>Vote Count</th>
      </tr>
       <% @poll.poll_answers.each do |ei| %>
           <tr>
             <td>
               <%= ei.title %>
             </td>
             <td>
                <%= ei.voteCount %>
             </td>
          <% end %>
    </table>
 
 <%@poll.votes.each do |ei| %>
      <% if ei.userId == current_user.id %>
       <% @voteStatus = 1 %>
     <% end %>
   <% end %>
 
    
 <% if @voteStatus != 1 %>
  <%= link_to vote_poll_path(poll_id: @poll.id), class: "new-instance-button",
            remote: true do %>
              <button class="btn-lg btn-primary">Vote</button>
      <% end %>
    <% else %>
    <h3>You have already voted!</h3>
  
  <% end %>
  
  <% @answers = [] %>
<% @datapoints = [] %>
<% @poll.poll_answers.each do |ei|
    
    @answers.push(ei.title)
    @datapoints.push(ei.voteCount)
end
%> 


<canvas id="myChart2" width="500" height="200"></canvas>
<script>
var ctx = document.getElementById("myChart2");
var myChart2 = new Chart(ctx, {
    type: 'pie',
  data: {
    labels: <%= raw @answers.to_json %>,
    datasets: [{
      backgroundColor: [
        "#2ecc71",
        "#3498db",
        "#95a5a6",
        "#9b59b6",
        "#f1c40f",
        "#e74c3c",
        "#34495e"
      ],
      data: <%= raw @datapoints.to_json %>
    }]
  }
});
</script>

app/views/shared/_poll_answers_vote_list.html.erb
<% @poll.poll_answers.each do |ft| %>
  <div class="poll-container">
    <span class="name">
      <%= link_to ft.title, poll_answer_path(ft) %>
    </span>
    <span class="actions">
      <%= link_to edit_poll_answer_path(ft),
      data: { confirm: "Are you sure?",
      message: "The poll vote will be recorded.",
      }, remote: true, title: "Vote" do %>
        <button class="btn-xs btn-primary btn-block">Vote</button>
      <% end %>
    </span>
  </div>
<% end %>

app/views/shared/_polls_list.html.erb
<% @event.polls.each do |ft| %>
  <div class="poll-container">
    <span class="name">
      <%= link_to ft.name, poll_path(ft) %>
    </span>
    <span class="actions">
      <% if can? :manage, @event %>
      <%= link_to edit_poll_path(ft), remote: true, title: "Edit" do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to poll_path(ft), method: :delete,
      data: { confirm: "Are you sure?",
      message: "The poll's information will be lost and cannot be recovered.",
      }, remote: true, title: "Delete" do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
    </span>
  </div>
<% end %>

app/views/shared/_uninvite_users_list.html.erb
  <table class="main-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Uninvite</th>
      </tr>
    </thead>
    <tbody>
      <% @invitation.each do |inv| %>
            <tr>
              <td><%= inv.user.username %></td>
              <td>
                <%= link_to remove_invite_event_path(inv), method: :delete,
                data: {confirm: "Are you sure?",
                message: "The user will be removed from the invitees list.",
                }, remote: true, title: "Delete" do %>
                  <%= fa_icon "trash" %>
          <% end %>    
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>