config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :poll_answers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user_token' => 'user_token#create'

  root to: 'statics#home'

  as :user do
    # sessions
    get     'login',  to: 'devise/sessions#new',      as: :new_user_session
    post    'login',  to: 'devise/sessions#create',   as: :user_session
    delete  'logout', to: 'devise/sessions#destroy',  as: :destroy_user_session

    #registrations
    get   'users/cancel', to: 'devise/registrations#cancel',        as: :cancel_user_registration
    get   :signup,        to: 'devise/registrations#new',           as: :new_user_registration
    get   :profile,       to: 'devise/registrations#edit',          as: :edit_user_registration
    patch :profile,       to: 'devise_custom/registrations#update', as: :update_user_registration
  end
  devise_for :users, skip: [:sessions], controllers: { registrations: 'devise_custom/registrations' }


  get '/dashboard' , to: 'dashboard#index'
  get :dashboard, to: 'dashboard#index', as: :dashboard_index


 # get '/events/invite_event' , to: 'events#invite_event'
  get '/events/uninvite_event' , to: 'events#uninvite_event'
  get '/events/invite_app' , to: 'events#invite_app'
  get '/events/accept_event/:id' , to: 'events#accept_event', as: :accept_event_invite

  get '/events/qrcode/:id', to: 'events#qrcode', as: 'qrcode_event'
  get '/event_instances/qrcode/:id', to: 'event_instances#qrcode', as: 'qrcode_event_instance'
  post '/attendances/attended/', to: 'attendances#attended', as: 'attendances_attended'
  get '/attendances/doneattendance/', to: 'attendances#doneattendance', as: 'attendances_doneattendance'

  resources :events
  resources :event_instances, only: :destroy

  resources :events do
    member do
      get   :invite_event
      post  :invite_event_errors
      post  :accept_invitation_event
      post  :invite_app_action
      delete  :remove_invite
      delete   :leave_event
    end
  end
  resources :event_instances
  resources :polls do
    member do
      get :vote
    end
  end
  resources :forum_threads
  resources :attachments
  resources :comments
  resources :attendances



  # api
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events do
        post :invite, on: :member
      end
      resources :event_instances do
        post :mark_present, on: :member
      end
    end
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_instances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invited_users, through: :invitations, source: :user
  has_many :polls, dependent: :destroy
  has_many :forum_threads, dependent: :destroy
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :event_instances
  validates :name, presence: true

  def self.RECURRENT_DAYS
    {
      "No recurrent": 0,
      "Sunday": 1,
      "Monday": 2,
      "Tuesday": 3,
      "Wednesday": 4,
      "Thursday": 5,
      "Friday": 6,
      "Saturday": 7
    }
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1

    class EventsController < ApplicationController

      def index
        @events = User.find(params[:user_id]).events.includes(:event_instances)
      end

      def invite
        event = Event.find_by(id: params[:id])
        if event.blank? || !event.open
          render json: { status: "Bad Request", error: "Event not found" }, status: 400 and return
        end
        if event.invitations.where(user_id: params[:user_id]).count > 0
          render json: { status: "Bad Request", error: "You are already invited" }, status: 400 and return
        end
        inv = event.invitations.build(user_id: params[:user_id])
        inv.save
        # send email
        render json: { status: "ok" }, status: :ok
      end

    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  include EventsConcern
  
  def invite_event
   @event = Event.find(params[:id])
  end

  def uninvite_event
   @event = Event.find(params[:id])
   @invitation = @event.invitations
  end
  
  def invite_app
  end
  
  def invite_app_action
    NotificationMailer.invite_app_email(params['enter_email'], current_user).deliver_now
  end
  
  def accept_event
    @event = Event.find(params[:id])
    @user = current_user
  end
  
  def accept_invitation_event
    @event = Event.find(params[:id])
    @invitation = Invitation.find_by(event_id: @event.id, user_id: current_user.id)
    if @invitation == nil
       Invitation.create(:event_id=> @event.id, :user_id=> current_user.id)
    end
  end
  
  def remove_invite
    @invitation_remove = Invitation.find(params[:id])
    @invitation = @invitation_remove.event.invitations
    @invitation_remove.destroy
  end
  
  def leave_event
    @event = Event.find(params[:id])
    @invitation_remove = Invitation.find_by(user_id: current_user.id, event_id: @event.id )
    @invitation_remove.destroy
  end  
  
  def show
    @event = EventInstance.find(params[:id]).event
  end

  def new
    @event = current_user.events.build
    @event.event_instances.build
  end

  def create
    @event = current_user.events.build event_params
    @event.save
    e = Event.find(@event.id)
    ei = e.event_instances.first
    location = ei.location
    date = ei.date
    r = e.recurrent
    for i in 0..r-1
      date = date + 7.days
      e.event_instances.create(:location=> location,:date=> date)
    end 
      get_event_instances
  end

  def edit
    @event = EventInstance.find(params[:id]).event
    @event_instance_id = params[:id]
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes event_params
    get_event_instances
  end

  def invite_event_errors
    @event = Event.find(params[:id])
    @user = User.find_by(email: params[:user_email])
    if @user.blank?
      @event.errors.add(:base, "A user with the specified email was not found")
    else
       NotificationMailer.accept_invite_event(current_user, @user, @event).deliver_now
    end
  end
  
  def qrcode
    @event = Event.find(params[:id])
    qr = RQRCode::QRCode.new("i"+ @event.id.to_s, :size => 4, :level => :h ).to_img
    @qrimg = qr.resize(200, 200)
  end
  
  def destroy
    event = Event.find(params[:id])
    event.destroy
  end


  private

  def event_params
    params.require(:event).permit(:name, :recurrent,:open, event_instances_attributes: [
      :id, :date, :location
    ])
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.html.erb
<div class="header">
  <h2>Edit Event</h2>
</div>

<%= form_for @event, remote: true do |f| %>
  <div class="errors-container">
    <%= render 'shared/form_errors', object: @event %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :recurrent, "Repeat" %>
    <%= f.number_field :recurrent, class: "form-control" %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :open %> Open
    </label>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/events/_events_list.html.erb
<div class="main-table-container">
  <table class="main-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Recurrent</th>
        <th>Location</th>
        <th>Time</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% event_instances.each do |ei| %>
        <tr>
          <td><%= link_to ei.event.name, event_path(ei) %></td>
          <td>
            <%= ei.event.recurrent == 0 ? "No" : "#{ei.event.recurrent} times" %>
          </td>
          <td><%= ei.location %></td>
          <td><%= ei.date.strftime "%b %e, %Y @ %l:%M %P" %></td>
          <td>
            <% if can? :manage, ei %>
              <%= link_to edit_event_path(ei), remote: true, title: "Edit" do %>
                <%= fa_icon "pencil" %>
              <% end %>
              <%= link_to event_instance_path(ei), method: :delete,
              data: { confirm: "Are you sure?",
              message: "The event's information will be lost and cannot be recovered.",
              }, remote: true, title: "Delete" do %>
                <%= fa_icon "trash" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/_invite_app_form.html.erb
<div class="header">
  <h2>Invite friends to the system: </h2>
</div>
<br>

<%= form_tag invite_app_action_event_path(:enter_email), remote: true do %>

<div class: "form-group">
    <table align="center">
    <thead>
      <tr>
        <th> <%= label_tag :enter_email %> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
            <tr>
              <td style="width:72%"><%= email_field_tag :enter_email, "", class: "form-control" %></td>  
              <td> <button title= "Invite more ", id= "Invite_app_button", class="btn btn-primary", type= "submit"><%= fa_icon "user-plus" %> Submit </button>
                   </td>
            </tr>
        </tbody>
      </table>
    </div>
    <% end %>
</div>
  <br>
  
 <div class= "actions">
      <button id= "Button_done", class="btn btn-primary"> Done </button>
  </div>

app/views/events/_invite_form.html.erb
<div style="position: relative; left: -10px;",  class="header">
  <h1> Invite User to: </h1>
</div>

<div align= "center", class= "event_info">
    <h4> <%= @event.name %> </h4>
</div>

<%= form_tag invite_event_errors_event_path(id: @event.id), remote: true do %>
<div class="errors-container">
  <%= render 'shared/form_errors', object: @event %>
</div>

 <br>
 
  <div class="form-group">
        <table align="center">
    <thead>
      <tr>
        <th>  <%= label_tag :user_email %></th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
            <tr>
              <td style="width:70%"><%= email_field_tag :user_email, "", class: "form-control" %></td>
              <td>
                  <button id= "Invite_event_button", class="btn btn-primary", type= "submit"><%= fa_icon "user-plus" %> Submit </button>
            </td>
            </tr>
        </tbody>
        <% end %>
      </table>
  </div>
  
  
  <div class= "actions">
      <button id= "Button_done", class="btn btn-primary"> Done </button>
  </div>

app/views/events/_new_form.html.erb
<div class="header">
  <h2>New Event</h2>
</div>

<%= form_for @event, remote: true do |f| %>
<div class="errors-container">
  <%= render 'shared/form_errors', object: @event %>
</div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :recurrent, "Repeat" %>
    <%= f.number_field :recurrent, class: "form-control" %>
  </div>
   <div class="checkbox">
    <label>
      <%= f.check_box :open %> Open
    </label>
  </div>

  <%= f.fields_for :event_instances do |ei| %>
    <div class="form-group">
      <%= ei.label :date, "Date and Time:" %>
      <%= ei.datetime_select :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= ei.label :location %>
      <%= ei.text_area :location, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/events/_qrcode_form.html.erb
<div class="header">
  <h2>Invitations QR Code</h2>
</div>
 <%if @event.open %>
<div id="toprint">
   
    <div class="clearfix text-center">
        
        <div class="form-group">
            <h3>Event:  <%= @event.name %></h3>
        </div>
        
    </div>
  
   
    <div class="clearfix" style="padding:5px">
            <div class="thumbnail">
                <img src=" <%=@qrimg.to_data_url%>" />
            </div>
        
        
    </div>
    <h4>Please scan qrcode using our app to invite yourself to this event</h4>
    
     </div>
     
        <div class="actions">
            <button onclick="PrintElem('toprint')"  class="btn btn-success">Print Code</button>
       </div>
       
        <%else%>
        <div class="clearfix text-center">
          <h3 class="alert-danger">  This is a close event. An invitations qr code cannot be provided. </h3>
        </div>
         <%end%>
   
   
<script>
    function PrintElem(elem)
{
    var mywindow = window.open('', 'PRINT');
    
    mywindow.document.write('<html><head><title>' + document.title  + '</title>');
    mywindow.document.write("</head><body><div style='width:100%; text-align:center'");
    mywindow.document.write('<h1>' + document.title  + '</h1>');
    mywindow.document.write(document.getElementById(elem).innerHTML);
    mywindow.document.write('</div></body></html>');

    mywindow.document.close(); // necessary for IE >= 10
    mywindow.focus(); // necessary for IE >= 10*/

setTimeout(function() {
    mywindow.print();
    mywindow.close();
}, 250);
    

    return true;
}
</script>

app/views/events/_uninvite_form.html.erb
 <h2 align= "center"> Uninvite User </h2>
<div class="main-table-container">
    <%= render 'shared/uninvite_users_list'%>
</div>
    
 <div class= "actions">
      <button id= "Button_done", class="btn btn-primary active btn-lg"> Done</button>
  </div>

app/views/events/accept_event.html.erb
<div style= "width: 50%; position: absolute; left: 250px; top: 80px;", class="event-info">

<div class="header">
      <h1> Accept invitation to: </h1>
  </div>
<div class= "form-group">
    <h4> <%= @event.name %> </h4>
</div>

<br>
<br>
<br>

  <div class= "actions">
    <%= link_to accept_invitation_event_event_path(id: @event.id), method: :post, class: "btn btn-primary active btn-lg", remote: true do %> 
        <%= fa_icon "check" %> 
        Accept
    <% end %>
    
    <%= link_to '/dashboard',
      class: "btn btn-primary active btn-lg" do %><%= fa_icon "close" %>
      Decline
     <% end %> 
  </div>

</div>

app/views/events/show.html.erb
<div class="event-info">
  <h2><%= @event.name %></h2>
  <h5>Event Admin:</h5>
  <h5><i><%= @event.user.username %></i></h5>


 <%= link_to events_invite_app_path,
  class: "invite-user-button", title: "Invite friends to app", remote: true do %>
  <%= fa_icon "bullhorn" %>
  <% end %>

  <h5>Number of Invitees: <%= @event.invitations.count %></h5>
</div>

<div class="container event-container">
  <div class="row">
     <div class="col-sm-12">
        <div class="panel panel-default events_instances-card">
          <div class="panel-heading">
            <h3 class="panel-title">
              Event Instances
              <%= link_to new_event_instance_path(id: @event.id), class: "new-instance-button",
              remote: true do %>
                <%= fa_icon "plus" %>
              <% end %>
            </h3>
          </div>

          <div class="panel-body">
            <%= render 'shared/events_instances_list' %>
          </div>
        </div>
      </div>
  </div>
</div>

<div class="container event-container">
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default forums-card event-card">
        <div class="panel-heading">
          <h3 class="panel-title">
            Forums
            <%= link_to new_forum_thread_path(event_id: @event.id), class: "new-instance-button",
            remote: true do %>
              <%= fa_icon "plus" %>
            <% end %>
          </h3>
        </div>

        <div class="panel-body">
          <%= render 'shared/forum_threads_list' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default attachments-card event-card">
        <div class="panel-heading">
          <h3 class="panel-title">Attachments
            <% if can? :manage, @event %>
              <%= link_to new_attachment_path(event_id: @event.id), class: "new-instance-button",
              remote: true do %>
                <%= fa_icon "plus" %>
              <% end %>
            <% end %>
          </h3>
        </div>

        <div class="panel-body">
          <%= render 'shared/attachments_list' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default polls-card even-card">
        <div class="panel-heading">
          <h3 class="panel-title">
            Polls
             <% if can? :manage, @event %>
            <%= link_to new_poll_path(event_id: @event.id), class: "new-instance-button",
            remote: true do %>
              <%= fa_icon "plus" %>
            <% end %>
            <% end %>
          </h3>
        </div>

        <div class="panel-body">
          <%= render 'shared/polls_list' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default other-card">
        <div class="panel-heading">
          <h3 class="panel-title">Other Options </h3>
        </div>

        <div class="panel-body">
            <div>
              <%= link_to invite_event_event_path(id: @event.id), remote: true do %>
              Invite User
              <% end %>
            </div>
            <div>
              <%= link_to events_uninvite_event_path(id: @event.id), remote: true do %>
              Uninvite User
              <% end %>
            </div>
            <%if @event.open%>
            <%= link_to qrcode_event_path(id: @event.id), class: "new-instance-button",
                remote: true do %>
                Print Invitations QR Code <% end %><br/>
                <%end%>

          <div>
            <%= link_to events_uninvite_event_path(id: @event.id), remote: true do %>
              Uninvite users
            <% end %>
          </div>
        
         <%= link_to event_path(id: @event.id), method: :delete,
              data: { confirm: "Are you sure?",
              message: "The event's information will be lost and cannot be recovered. All the event instances will also be removed",
              }, remote: true, title: "Delete" do %>
               Delete Event
              <% end %>
        </div>
      </div>
    </div>
  </div>
</div>