config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :poll_answers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user_token' => 'user_token#create'

  root to: 'statics#home'

  as :user do
    # sessions
    get     'login',  to: 'devise/sessions#new',      as: :new_user_session
    post    'login',  to: 'devise/sessions#create',   as: :user_session
    delete  'logout', to: 'devise/sessions#destroy',  as: :destroy_user_session

    #registrations
    get   'users/cancel', to: 'devise/registrations#cancel',        as: :cancel_user_registration
    get   :signup,        to: 'devise/registrations#new',           as: :new_user_registration
    get   :profile,       to: 'devise/registrations#edit',          as: :edit_user_registration
    patch :profile,       to: 'devise_custom/registrations#update', as: :update_user_registration
  end
  devise_for :users, skip: [:sessions], controllers: { registrations: 'devise_custom/registrations' }


  get '/dashboard' , to: 'dashboard#index'
  get :dashboard, to: 'dashboard#index', as: :dashboard_index


 # get '/events/invite_event' , to: 'events#invite_event'
  get '/events/uninvite_event' , to: 'events#uninvite_event'
  get '/events/invite_app' , to: 'events#invite_app'
  get '/events/accept_event/:id' , to: 'events#accept_event', as: :accept_event_invite

  get '/events/qrcode/:id', to: 'events#qrcode', as: 'qrcode_event'
  get '/event_instances/qrcode/:id', to: 'event_instances#qrcode', as: 'qrcode_event_instance'
  post '/attendances/attended/', to: 'attendances#attended', as: 'attendances_attended'
  get '/attendances/doneattendance/', to: 'attendances#doneattendance', as: 'attendances_doneattendance'

  resources :events
  resources :event_instances, only: :destroy

  resources :events do
    member do
      get   :invite_event
      post  :invite_event_errors
      post  :accept_invitation_event
      post  :invite_app_action
      delete  :remove_invite
      delete   :leave_event
    end
  end
  resources :event_instances
  resources :polls do
    member do
      get :vote
    end
  end
  resources :forum_threads
  resources :attachments
  resources :comments
  resources :attendances



  # api
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events do
        post :invite, on: :member
      end
      resources :event_instances do
        post :mark_present, on: :member
      end
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is? :admin
      can :manage, :all
    elsif user.is? :regular
      can :manage, Event, user_id: user.id
      can :manage, EventInstance, event: { user_id: user.id }
      can :manage, Attachment, event: { user_id: user.id }
      can :show, Attachment
      can :manage, ForumThread, event: { user_id: user.id }
      can :manage, ForumThread, user_id: user.id
      can :manage, Comment, forum_thread: { event: { user_id: user.id } }
      can :manage, Comment, forum_thread: { user_id: user.id }
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to      :event
  mount_uploader  :file,  FileUploader # Tells rails to use this uploader for this model.
  #validates       :user,        presence: true # Make sure the user is event admin.
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event_instance
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :forum_thread
  has_ancestry

  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_instances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :invited_users, through: :invitations, source: :user
  has_many :polls, dependent: :destroy
  has_many :forum_threads, dependent: :destroy
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :event_instances
  validates :name, presence: true

  def self.RECURRENT_DAYS
    {
      "No recurrent": 0,
      "Sunday": 1,
      "Monday": 2,
      "Tuesday": 3,
      "Wednesday": 4,
      "Thursday": 5,
      "Friday": 6,
      "Saturday": 7
    }
  end
end

app/models/event_instance.rb
class EventInstance < ApplicationRecord
  belongs_to :event
  has_many :attendances, dependent: :destroy
  validates :date, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :event
  has_many :poll_answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :name, presence: true
end

app/models/poll_answer.rb
class PollAnswer < ApplicationRecord
  belongs_to :poll
  validates :title, presence: true
  
  

def default_values
  self.voteCount = 0
end

def name
    "#{title}"
end

end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic

  ROLES = %w[ admin regular ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable

  alias_method :authenticate, :valid_password?

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :events, dependent: :destroy
  has_many :event_instances, through: :events
  has_many :attendances, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :forum_threads, dependent: :destroy
  has_many :comments, dependent: :destroy

  def is?(role)
    roles.include?(role.to_s)
  end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def self.from_token_payload payload
    self.find payload["user_id"]
  end

  def to_token_payload
    {
      user_id: id.to_s,
      custom: {
        name: username,
        email: email
      }
    }
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
    
    belongs_to :poll
   
   
    def default_values
      self.userId = -1
    end
    
    def default_values
      self.pollAnswerId = -1
    end
  
        
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  
  def new
    event = Event.find(params[:event_id])
    @poll = event.polls.build
  end
  
  def create
    event = Event.find(params[:event_id])
    @poll = event.polls.build poll_params
    @poll.save
    @event = Event.find(params[:event_id])
  end

  def show
    @poll = Poll.find(params[:id])
    @voteStatus = 0
    @userId = current_user.id
    @poll.votes.each do |ei|
      if ei.userId == current_user.id
        @voteStatus = 1
      end
    end
  end
  
  
  def vote
    @poll = Poll.find(params[:id])
    poll = Poll.find(params[:id])
    event = Event.find(@poll.event_id)
    
    vote = Vote.create()
    vote.userId = current_user.id
    vote.poll = poll
    vote.save
    @poll.save
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.update_attributes(poll_params)
    @event = @poll.event
  end

  def destroy
    @poll = Poll.find(params[:id])
    @event = @poll.event
    @poll.destroy
  end

  private
  def poll_params
    params.require(:poll).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def render_comments comments
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, render_comments(sub_comments), class: "nested-comments")
    end.join.html_safe
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
      <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/general_helper.rb
module GeneralHelper

  def set_title

  end

end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/polls/_edit_form.html.erb
<div class="header">
  <h2><%= params[:action] == "new" ? "New" : "Edit" %> Poll</h2>
</div>
<%= form_for @poll, remote: true do |f| %>
  <div class="errors-container">
    <%= render 'shared/form_errors', object: @poll %>
  </div>

  <%= hidden_field_tag :event_id, @poll.event_id %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="col-sm-14">
        <div class="panel panel-default polls-card even-card">
          <div class="panel-heading">
            <h3 class="panel-title">
              Poll Answers
              <%= link_to new_poll_answer_path(poll_id: @poll.id), class: "new-instance-button",
              remote: true do %>
                <%= fa_icon "plus" %>
              <% end %>
            </h3>
          </div>
          <div class="panel-body">
            <%= render 'shared/poll_answers_list' %>
          </div>
        </div>
      </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

    



</div>

app/views/polls/_new_edit_form.html.erb
<div class="header">
  <h2><%= params[:action] == "new" ? "New" : "Edit" %> Poll</h2>
</div>

<%= form_for @poll, remote: true do |f| %>
  <div class="errors-container">
    <%= render 'shared/form_errors', object: @poll %>
  </div>

  <%= hidden_field_tag :event_id, @poll.event_id %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/polls/_vote_form.html.erb
<div class="header">
  <h2>Vote</h2>
</div>

 <div class="col-sm-14">
        <div class="panel panel-default polls-card even-card">
         
          <div class="panel-body">
            <%= render 'shared/poll_answers_vote_list' %>
          </div>
        </div>
      </div>

app/views/polls/show.html.erb
<div class="forum-info">
  <h2>Poll: <%= @poll.name %></h2>
</div>

<h2>Results</h2>

<div class="container event-container">
<div class="row">
    
    <% if @poll.poll_answers.count == 0%>
        <h3>Event admin has not poll answers yet.</h3>
    <% else %>
    
   <div class="col-sm-12">
      <div class="panel panel-default polls-card">
        <div class="panel-body">
             <%= render "shared/poll_answers_table" %>
        </div>
      </div>
    </div>
    
    <%end%>

</div>