config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  resources :poll_answers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'user_token' => 'user_token#create'

  root to: 'statics#home'

  as :user do
    # sessions
    get     'login',  to: 'devise/sessions#new',      as: :new_user_session
    post    'login',  to: 'devise/sessions#create',   as: :user_session
    delete  'logout', to: 'devise/sessions#destroy',  as: :destroy_user_session

    #registrations
    get   'users/cancel', to: 'devise/registrations#cancel',        as: :cancel_user_registration
    get   :signup,        to: 'devise/registrations#new',           as: :new_user_registration
    get   :profile,       to: 'devise/registrations#edit',          as: :edit_user_registration
    patch :profile,       to: 'devise_custom/registrations#update', as: :update_user_registration
  end
  devise_for :users, skip: [:sessions], controllers: { registrations: 'devise_custom/registrations' }


  get '/dashboard' , to: 'dashboard#index'
  get :dashboard, to: 'dashboard#index', as: :dashboard_index


 # get '/events/invite_event' , to: 'events#invite_event'
  get '/events/uninvite_event' , to: 'events#uninvite_event'
  get '/events/invite_app' , to: 'events#invite_app'
  get '/events/accept_event/:id' , to: 'events#accept_event', as: :accept_event_invite

  get '/events/qrcode/:id', to: 'events#qrcode', as: 'qrcode_event'
  get '/event_instances/qrcode/:id', to: 'event_instances#qrcode', as: 'qrcode_event_instance'
  post '/attendances/attended/', to: 'attendances#attended', as: 'attendances_attended'
  get '/attendances/doneattendance/', to: 'attendances#doneattendance', as: 'attendances_doneattendance'

  resources :events
  resources :event_instances, only: :destroy

  resources :events do
    member do
      get   :invite_event
      post  :invite_event_errors
      post  :accept_invitation_event
      post  :invite_app_action
      delete  :remove_invite
      delete   :leave_event
    end
  end
  resources :event_instances
  resources :polls do
    member do
      get :vote
    end
  end
  resources :forum_threads
  resources :attachments
  resources :comments
  resources :attendances



  # api
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events do
        post :invite, on: :member
      end
      resources :event_instances do
        post :mark_present, on: :member
      end
    end
  end

end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def new
    event = Event.find(params[:event_id])
    @forum_thread = event.forum_threads.build
  end

  def create
    event = Event.find(params[:event_id])
    @forum_thread = event.forum_threads.build forum_thread_params
    if @forum_thread.save
      @forum_thread.update_attribute(:user_id, current_user.id)
      NotificationMailer.forum_thread_created(@forum_thread).deliver_later
    end
    @event = Event.find(params[:event_id])
  end

  def show
    @forum_thread = ForumThread.find(params[:id])
  end

  def edit
    @forum_thread = ForumThread.find(params[:id])
  end

  def update
    @forum_thread = ForumThread.find(params[:id])
    if @forum_thread.update_attributes(forum_thread_params)
      NotificationMailer.forum_thread_updated(@forum_thread).deliver_later
    end
    @event = @forum_thread.event
  end

  def destroy
    @forum_thread = ForumThread.find(params[:id])
    @event = @forum_thread.event
    @forum_thread.destroy
    NotificationMailer.forum_thread_destroyed(@event, @forum_thread.title).deliver_later
  end

  private

  def forum_thread_params
    params.require(:forum_thread).permit(:title)
  end

end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_threads/_new_edit_form.html.erb
<div class="header">
  <h2><%= params[:action] == "new" ? "New" : "Edit" %> Forum Thread</h2>
</div>

<%= form_for @forum_thread, remote: true do |f| %>
  <div class="errors-container">
    <%= render 'shared/form_errors', object: @forum_thread %>
  </div>

  <%= hidden_field_tag :event_id, @forum_thread.event_id %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/forum_threads/show.html.erb
<div class="forum-info">
  <h2><%= @forum_thread.title %></h2>
  <h5>Created by:</h5>
  <h5><i><%= @forum_thread.user.username %></i></h5>
</div>
 
<div class="container forum-container">
  <h2 class="heading-center">Comments</h2>

  <div class="comments-container">
    <div class="comments-list">
      <%= render_comments @forum_thread.comments.arrange(order: :created_at) %>
    </div>
    <div class="well well-sm">
      <%= form_tag comments_path(forum_thread_id: params[:id]), method: :post, remote: true do %>
        <div class="form-group">
          <%= label_tag "new_parent_comment", "New comment" %>
          <%= text_area_tag "comment[body]", "", class: "form-control", id: "new_parent_comment" %>
        </div>
 
        <div class="actions">
          <%= submit_tag "Comment", class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>